# Generated by Django 4.1 on 2022-08-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('synopsis', models.CharField(max_length=2500)),
                ('copies', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('copies', models.IntegerField(default=1, null=True)),
                ('max_date', models.DateField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rental_id', 'movie_id')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='loans',
            field=models.ManyToManyField(related_name='borrowings', through='movies.Rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
