# Generated by Django 4.1 on 2022-08-16 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_rentals_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentals',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
