# Generated by Django 4.1 on 2022-08-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_rentals_unique_together_alter_rentals_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rented_copies',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
